/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: cab8de2adb31b9c67f34469ca19f1038)
interface __BaseEnv_Env {
	DB: D1Database;
	AUDIT_HITS: AnalyticsEngineDataset;
	CF_VERSION: WorkerVersionMetadata;
	ASSETS: Fetcher;
	SITE_NAME: "SHUFL";
	SITE_URL: "https://shufl.cybush.uk";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SITE_NAME" | "SITE_URL">> {}
}
