#!/usr/bin/env node
/**
 * Writes src/version.generated.ts before typecheck, test, or deploy.
 * SHA: WORKERS_CI_COMMIT_SHA (Workers Builds) → GITHUB_SHA (Actions) → git → "dev".
 */
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outFile = join(root, "src", "version.generated.ts");

function shortSha() {
  const fromEnv = (process.env.WORKERS_CI_COMMIT_SHA || process.env.GITHUB_SHA || "").trim();
  if (fromEnv) return fromEnv.slice(0, 7);
  try {
    const sha = execFileSync("git", ["rev-parse", "--short=7", "HEAD"], {
      cwd: root,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
    if (sha) return sha.slice(0, 7);
  } catch {
    // Shallow or non-git checkout.
  }
  return "dev";
}

const sha = shortSha();
const built = new Date().toISOString();
const source = `// Generated by scripts/write-version.mjs. Do not edit.
export const SHA = ${JSON.stringify(sha)};
export const BUILT = ${JSON.stringify(built)};
`;

writeFileSync(outFile, source);
console.log(`version ${sha} built ${built}`);
